#!/usr/bin/env python3
"""
Batch Remediation Script for Invalid PubChem Compound IRIs in ChemKG TTL Files

Overview
--------
This script performs a one-time batch correction on Turtle (.ttl) metadata files
generated by a previous version of the using_linkml_dataclasses.py. It fixes a bug
where failed PubChem API lookups resulted in invalid Compound IRIs ending in
"/compound/None" instead of falling back to a local dataset identifier.

Problem Context
---------------
The original ingestion script (_get_pubchem_cid) constructed PubChem URLs
unconditionally, even when the API returned None (due to network errors,
timeouts, or missing compounds). This produced invalid RDF triples like:
    <https://pubchem.ncbi.nlm.nih.gov/compound/None> a CHEBI:23367 ...

This violates linked data standards, as "None" is not a valid PubChem CID.

Correction Logic
----------------
For every file ending in '_dcat-ap-plus.ttl' or '_chem-dcat-ap.ttl':
1. Scans for the specific error string: "<https://pubchem.ncbi.nlm.nih.gov/compound/None>"
2. If found, extracts the main Dataset IRI from the line: "<[Dataset_IRI]> a dcat:Dataset"
3. Constructs a valid local fallback IRI: "<[Dataset_IRI]#sample_compound>"
4. Replaces the invalid PubChem link with the local fallback IRI.
5. Skips files that already contain valid CIDs (e.g., "/compound/12345") or
   do not contain the error string.

Usage
-----
    python fix_get_pubchem_cid_script.py

Note: The target folder path is hardcoded within the script for this single-use operation.
      Ensure the virtual environment is active before running.

Author: Philip Strömert
Date: 2026-05-01
"""
import re
import os
import sys

# --- CONFIGURATION ---
# Hardcoded folder path
TARGET_FOLDER = r"C:\Users\stroemertp\Nextcloud\SearchServiceTTLs"


# ---------------------

def fix_compound_iri_in_file(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except PermissionError:
        print(f"Permission denied (file might be syncing): {file_path}")
        return False
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
        return False

    error_string = "<https://pubchem.ncbi.nlm.nih.gov/compound/None>"

    # Skip if error string not found
    if error_string not in content:
        return False

    # Pattern: Capture IRI inside < > before 'a dcat:Dataset'
    dataset_iri_pattern = r'<([^>]+)>\s+a\s+dcat:Dataset'

    match = re.search(dataset_iri_pattern, content)

    if not match:
        print(f"Warning: Could not find dataset definition in {os.path.basename(file_path)}. Skipping.")
        return False

    dataset_iri = match.group(1)
    replacement_iri = f"<{dataset_iri}#sample_compound>"

    new_content = content.replace(error_string, replacement_iri)

    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"Fixed: {os.path.basename(file_path)}")
        return True
    except PermissionError:
        print(f"Permission denied writing to: {file_path}. Is Nextcloud syncing?")
        return False
    except Exception as e:
        print(f"Error writing to {file_path}: {e}")
        return False


def main():
    if not os.path.isdir(TARGET_FOLDER):
        print(f"Error: The hardcoded path does not exist or is not a folder:")
        print(f"       {TARGET_FOLDER}")
        sys.exit(1)

    fixed_count = 0
    skipped_count = 0
    total_count = 0

    target_suffixes = ("_dcat-ap-plus.ttl", "_chem-dcat-ap.ttl")

    print(f"Starting batch fix in: {TARGET_FOLDER}")
    print("-" * 50)

    for root, _, files in os.walk(TARGET_FOLDER):
        for filename in files:
            if filename.endswith(target_suffixes):
                total_count += 1
                file_path = os.path.join(root, filename)

                if fix_compound_iri_in_file(file_path):
                    fixed_count += 1
                else:
                    skipped_count += 1

    print("-" * 50)
    print(f"Processing complete.")
    print(f"Total relevant files found: {total_count}")
    print(f"Files fixed:                {fixed_count}")
    print(f"Files skipped (no error):   {skipped_count}")


if __name__ == "__main__":
    main()