"""
NFDI4Chem Search Service nmrXiv ID normalization script part 3 (Validation Step)

DESCRIPTION:
    This script acts as the final quality assurance (QA) step in the Search Service nmrXiv ID normalization
    workflow. It verifies that every ID from your original nmrXiv ID source list has been successfully mapped
    to a normalized nmrXiv ID using the dictionary generated by 'get_normalized_nmrxiv_ids_pt1.py' and
    'get_normalized_nmrxiv_ids_pt2.py'.

    It performs a strict completeness check:
    1. Compares the original list of unnormalized IDs against the generated mapping dictionary.
    2. Identifies any missing mappings (IDs that were not processed or failed).
    3. If ANY IDs are missing, the script halts with an error (Exit Code 1) to prevent incomplete data usage.
    4. If ALL IDs are present, it exports two clean, verified files for downstream use.

WORKFLOW CONTEXT:
    This script must be run AFTER:
    1. 'get_normalized_nmrxiv_ids_pt1.py' has finished processing all batches.
    2. 'get_normalized_nmrxiv_ids_pt2.py' has generated the final 'final_mapping.json'.

    It ensures that the parallel processing did not lose any data and that your final dataset
    is 100% complete before you proceed to analysis or file verification.

OUTPUTS (Generated only on 100% Success):
    1. 'normalized_mapping.json': A verified dictionary {original_id: normalized_id} containing
       ONLY the IDs present in your input list (filters out any extra noise if present).
    2. 'normalized_ids_only.json': A clean JSON list of purely normalized IDs, ordered exactly
       like the original input list. This is the ready-to-use file for verification or ingestion.

BEHAVIOR:
    - Success: Prints "✅ SUCCESS", exports both files, and exits with code 0.
    - Failure: Prints "❌ VALIDATION FAILED", lists missing IDs, skips export, and exits with code 1.
      (This allows you to use this script in automated pipelines to stop execution if data is incomplete).

USAGE:
    python get_normalized_nmrxiv_ids_pt3.py <input_keys_list.json> <mapping_dict.json>

    Arguments:
        input_keys_list.json : The original list of unnormalized IDs (the "source of truth" for what is needed).
        mapping_dict.json    : The full dictionary generated by 'convert_outputs.py' (type 'map').

EXAMPLE:
    # Verify that all IDs from 'original_batch.json' are present in 'final_mapping.json'
    python get_normalized_nmrxiv_ids_pt3.py original_batch.json final_mapping.json

    # If successful, you will get:
    # - normalized_mapping.json (Verified subset)
    # - normalized_ids_only.json (Clean list for next steps)
"""
import json
import sys
import os

def load_key_list(filename):
    """Loads a JSON file expecting a list of keys (unnormalized IDs)."""
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            data = json.load(f)
            if not isinstance(data, list):
                print(f"Error: {filename} must contain a JSON list of keys.")
                sys.exit(1)
            # Preserve order for reporting, create set for logic
            return [str(item) for item in data], set(str(item) for item in data)
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"Error: '{filename}' is not valid JSON.")
        sys.exit(1)

def load_mapping_dict(filename):
    """Loads a JSON file expecting a dict {unnormalized: normalized}."""
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            data = json.load(f)
            if not isinstance(data, dict):
                print(f"Error: {filename} must contain a JSON object (dict).")
                sys.exit(1)
            return data
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        sys.exit(1)
    except json.JSONDecodeError:
        print(f"Error: '{filename}' is not valid JSON.")
        sys.exit(1)

def main():
    if len(sys.argv) != 3:
        print("Usage: python check_and_export_normalized.py <input_keys_list.json> <mapping_dict.json>")
        sys.exit(1)

    list_file = sys.argv[1]
    dict_file = sys.argv[2]

    # Output filenames
    mapping_output_file = "normalized_mapping.json"
    clean_list_output_file = "normalized_ids_only.json"

    print(f"Loading required keys from: {list_file}")
    required_keys_list, _ = load_key_list(list_file)

    print(f"Loading mapping dictionary from: {dict_file}")
    mapping_dict = load_mapping_dict(dict_file)

    missing_keys = []
    mapped_results = {}

    # 1. Perform the comparison
    for key in required_keys_list:
        if key in mapping_dict:
            mapped_results[key] = mapping_dict[key]
        else:
            missing_keys.append(key)

    print("\n--- Normalization Check Results ---")
    print(f"Total keys to check: {len(required_keys_list)}")
    print(f"Successfully normalized: {len(mapped_results)}")
    print(f"Missing normalization: {len(missing_keys)}")
    print("-" * 40)

    # 2. Handle Missing Keys
    if missing_keys:
        print(f"\n❌ VALIDATION FAILED: {len(missing_keys)} keys were not found in the dictionary.")
        print("The following keys are missing mappings:")
        for key in missing_keys:
            print(f"   - {key}")
        
        print(f"\n⚠️  Skipped exporting '{clean_list_output_file}' because the data is incomplete.")
        # Optional: Still save the partial mapping if you want, but usually we stop here for clean lists
        # with open(mapping_output_file, 'w', encoding='utf-8') as out:
        #     json.dump(mapped_results, out, indent=2)
        # print(f"   -> Saved partial mappings to '{mapping_output_file}'")
        
        sys.exit(1) # Exit with error code 1 to indicate failure

    # 3. Success Path: No differences found
    print(f"\n✅ SUCCESS: All {len(required_keys_list)} keys were found and normalized.")

    # Save the full mapping (Key -> Value)
    with open(mapping_output_file, 'w', encoding='utf-8') as out:
        json.dump(mapped_results, out, indent=2)
    print(f"   -> Saved full mapping to '{mapping_output_file}'")

    # 4. Export ONLY the list of normalized IDs
    # Extract just the values, preserving the order of the original input list
    normalized_ids_only = [mapped_results[key] for key in required_keys_list]

    with open(clean_list_output_file, 'w', encoding='utf-8') as out:
        json.dump(normalized_ids_only, out, indent=2)
    
    print(f"   -> Exported clean list of {len(normalized_ids_only)} normalized IDs to '{clean_list_output_file}'")
    print("\nDone!")

if __name__ == "__main__":
    main()