"""
NFDI4Chem Search Service nmrXiv ID normalization script part 2 (Finalization Step)

DESCRIPTION:
    This script converts intermediate '.jsonl' (JSON Lines) files generated by 'get_normalized_nmrxiv_ids_pt1.py'
    into standard '.json' files usable by downstream tools.

    It merges multiple lines of individual JSON objects (produced by parallel script instances)
    into a single, valid JSON structure.

WHY THIS IS NEEDED:
    - 'get_normalized_nmrxiv_ids_pt1.py' writes data line-by-line to allow safe parallel appending.
    - The resulting '.jsonl' files are NOT valid standard JSON (they lack outer brackets or braces).
    - This script reads all lines, aggregates them, and writes a clean, single JSON object/list.

INPUT FORMATS:
    1. List Mode ('list'):
       - Input: Lines of strings (e.g., "id1"\n"id2"\n).
       - Output: A JSON Array (e.g., ["id1", "id2"]).
       - Use for: The corrected ID list.

    2. Map Mode ('map'):
       - Input: Lines of single-key objects (e.g., {"old": "new"}\n{"old2": "new2"}\n).
       - Output: A single merged JSON Dictionary (e.g., {"old": "new", "old2": "new2"}).
       - Use for: Creating the ID mapping lookup table for nmrXiv IDs in the NFDI4Chem Search Service.

DEPENDENCIES:
    - Requires output files from 'get_normalized_nmrxiv_ids_pt1.py'.
    - Should only be run AFTER all parallel instances of 'get_normalized_nmrxiv_ids_pt1.py' have finished.

USAGE:
    python get_normalized_nmrxiv_ids_pt2.py <type> <input_jsonl> <output_json>

    Arguments:
        type        : Either 'list' (for ID lists) or 'map' (for ID mappings).
        input_jsonl : Path to the intermediate .jsonl file.
        output_json : Path to the final .json file to be created.

EXAMPLES:
    # Convert the list of corrected IDs
    python get_normalized_nmrxiv_ids_pt2.py list normalized_nmrxiv_ids.jsonl collection_nmrxiv_normalized.json

    # Convert the mapping dictionary
    python get_normalized_nmrxiv_ids_pt2.py map nmrxiv_ids_mapped.jsonl collection_nmrxiv_id_mapping.json
"""
import json
import sys

def convert_jsonl_to_json(input_file, output_file, is_mapping=False):
    results = []
    merged_dict = {}
    
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                if line.strip():
                    try:
                        item = json.loads(line)
                        if is_mapping:
                            # Expecting item to be a dict like {"old_id": "new_id"}
                            if isinstance(item, dict) and len(item) == 1:
                                old_key = next(iter(item.keys()))
                                new_val = item[old_key]
                                merged_dict[old_key] = new_val
                            else:
                                print(f"Warning: Skipping invalid mapping format on line {line_num}: {item}")
                        else:
                            results.append(item)
                    except json.JSONDecodeError as e:
                        print(f"Warning: Skipping invalid JSON on line {line_num} in {input_file}: {e}")
        
        with open(output_file, 'w', encoding='utf-8') as f:
            if is_mapping:
                # Write the single merged dictionary
                json.dump(merged_dict, f, indent=2, ensure_ascii=False)
                print(f"Successfully merged {len(merged_dict)} mappings from '{input_file}' to '{output_file}'")
            else:
                # Write the list
                json.dump(results, f, indent=2, ensure_ascii=False)
                print(f"Successfully converted {len(results)} items from '{input_file}' to '{output_file}'")
                
    except Exception as e:
        print(f"Error converting '{input_file}': {e}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python convert_outputs.py <type> <input_jsonl> <output_json>")
        print("  <type>: 'list' (for IDs) or 'map' (for mappings)")
        print("Example 1: python convert_outputs.py list results.jsonl final_ids.json")
        print("Example 2: python convert_outputs.py map mapping.jsonl final_mapping.json")
        sys.exit(1)

    file_type = sys.argv[1]
    input_file = sys.argv[2]
    output_file = sys.argv[3]

    if file_type == 'list':
        convert_jsonl_to_json(input_file, output_file, is_mapping=False)
    elif file_type == 'map':
        convert_jsonl_to_json(input_file, output_file, is_mapping=True)
    else:
        print("Error: Type must be 'list' or 'map'")
        sys.exit(1)