"""
File sorter for using_linkml_dataclasses.py output
-----------------------------
This script organizes the bulk `.ttl` files generated by 'using_linkml_dataclasses.py'.
The using_linkml_dataclasses.py script processes datasets from five distinct repositories
ánd outputs all results into a single flat folder. Since the filenames start with
unique identifiers corresponding to their source repository (e.g., "nmrx...", "msbn...", "doi-..."),
this script groups the files into subfolders named after these prefixes.

This structure simplifies the final step of moving the processed files into the
respective output directories, avoiding manual sorting of hundreds of mixed files.

Usage:
    python sort_files.py [path_to_folder]
    If no path is provided, the script will prompt for one interactively.
"""
import os
import shutil
import sys

def sort_files_by_prefix(root_path, prefix_length=4):
    """
    Sorts files in the given directory into subfolders based on the first N characters of their filenames.
    
    :param root_path: The path to the directory containing the files.
    :param prefix_length: The number of characters to use for the folder name (default is 4).
    """
    if not os.path.isdir(root_path):
        print(f"Error: The path '{root_path}' does not exist or is not a directory.")
        return

    # Iterate over all items in the directory
    for filename in os.listdir(root_path):
        source_path = os.path.join(root_path, filename)

        # Skip if it's not a file (e.g., skip existing directories)
        if not os.path.isfile(source_path):
            continue

        # Determine the folder name based on the first N characters
        if len(filename) < prefix_length:
            # Optional: Decide how to handle files shorter than the prefix length
            # Here we just use the whole name if it's too short
            folder_name = filename
        else:
            folder_name = filename[:prefix_length]

        # Create the full path for the destination folder
        destination_folder = os.path.join(root_path, folder_name)

        # Create the folder if it doesn't exist
        if not os.path.exists(destination_folder):
            os.makedirs(destination_folder)
            print(f"Created folder: {destination_folder}")

        # Define the full destination path for the file
        destination_path = os.path.join(destination_folder, filename)

        # Move the file
        try:
            shutil.move(source_path, destination_path)
            print(f"Moved '{filename}' to '{folder_name}'")
        except Exception as e:
            print(f"Error moving file '{filename}': {e}")

if __name__ == "__main__":
    # Check if a path was provided as a command-line argument
    if len(sys.argv) > 1:
        target_path = sys.argv[1]
    else:
        # Fallback: Ask the user for input if no argument is provided
        target_path = input("Please enter the path to the folder you want to sort: ").strip('"')

    sort_files_by_prefix(target_path)